---
# Install Nginx web server
- name: Install Nginx
  apt:
    name: nginx
    state: present

# Configure Nginx securely
- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

# Start and enable Nginx service
- name: Start and enable Nginx service
  systemd:
    name: nginx
    enabled: yes
    state: started
