---
---
- name: Copy initial hardening script to the target system
  copy:
    src: hardening_script.sh
    dest: /tmp/hardening_script.sh
    owner: root
    group: root
    mode: '0755'

- name: Run initial hardening script
  command: /tmp/hardening_script.sh

- name: Install AIDE
  apt:
    name: aide
    state: present

- name: Copy AIDE configuration
  copy:
    src: aide.conf
    dest: /etc/aide/aide.conf
    owner: root
    group: root
    mode: '0644'

- name: Initialize AIDE database
  command: aideinit
  args:
    creates: /var/lib/aide/aide.db.gz


# Setup AIDE cron job
- name: Setup AIDE cron job
  cron:
    name: "AIDE daily check"
    job: "/usr/sbin/aide --check | mail -s 'AIDE Integrity Check Report' your@email.com"
    minute: 0
    hour: 3
    user: root

# Apply CIS Benchmark recommendations
- name: Apply CIS Benchmark recommendations
  command: cis-benchmark.sh
  args:
    creates: /var/log/cis_benchmark_done.log
