- hosts: webservers
  become: yes
  tasks:
    - name: Copy initial hardening script to the target system
      copy:
        src: roles/common/files/hardening_script.sh
        dest: /tmp/hardening_script.sh
        owner: root
        group: root
        mode: "0755"

    - name: Run initial hardening script
      command: /tmp/hardening_script.sh

    - name: Install AIDE
      apt:
        name: aide
        state: present

    - name: Copy AIDE configuration
      copy:
        src: roles/common/files/aide.conf
        dest: /etc/aide/aide.conf
        owner: root
        group: root
        mode: "0644"

    - name: Initialize AIDE database
      command: aideinit
      args:
        creates: /var/lib/aide/aide.db.gz

    - name: Install Apache web server
      apt:
        name: apache2
        state: present

    - name: Configure Apache to use secure settings
      copy:
        src: roles/webserver/files/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: "0644"

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes
