---
- name: Configure DNS Server
  hosts: dns_servers
  become: yes
  tasks:
    - name: Install BIND9
      apt:
        name: bind9
        state: present

    - name: Configure BIND9
      template:
        src: named.conf.options.j2
        dest: /etc/bind/named.conf.options

    - name: Restart BIND9
      systemd:
        name: bind9
        state: restarted
